### ISSUE TITLE
Inquiry Regarding Code for "Data Efficient Behavior Cloning for Fine Manipulation via Continuity-based Corrective Labels"

### ISSUE THREAD

**Issue by dadadadawjb** [personalrobotics/CCIL#2]
Hi team, 

Thanks for sharing the great work! I wonder if you could also share the source code for the experiments "[Data Efficient Behavior Cloning for Fine Manipulation via Continuity-based Corrective Labels](https://arxiv.org/abs/2405.19307)". I'm amazed by the performance CCIL achieves in the real-world robot experiments.

Thanks a lot!

**Comment by abhaybd** [comment]
A development version of the codebase used in that paper is in the [label-filtering](https://github.com/personalrobotics/CCIL/tree/label-filtering) branch, which is not officially released yet, but is publicly accessible. This branch includes the outlined additions, most importantly the improved label filtering algorithm.

We are slowly releasing the robot code framework that was used for policy deployment, but there are no immediate plans to release this publicly yet.
